###  FORMAT  ###

format = '[](red)[](green)[](yellow) [ ](cyan) $directory '

###  MISC  ###

add_newline = true

###  MODULES  ##

[time]
time_format = "%T"
format = "[ $time]($style)"
style = "cyan"
disabled = false

[directory]
style = "bold cyan"
truncation_length = 1
format = "[$path]($style)"

##  GIT  ##

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""
style = "bold yellow"

[git_status]
diverged = " [李${ahead_count} ${behind_count}](bold magenta)"
untracked = " [ ${count}](bold yellow)"
staged = " [⏽${count}](bold green)"
modified = "[凜${count}](bold blue)"
deleted = " [﫧${count}](bold red)"
format = " $modified$deleted$staged$untracked$diverged"
