###  FORMAT  ###

format = '[](bg:#464347 fg:#1e222a)$username$directory$git_branch$git_status$character'
add_newline = true

###  MODULES  ###

[character]
success_symbol = "[[](bg:#1e222a fg:#464347)](fg:#1e222a)"
error_symbol = "[[](bg:#1e222a fg:#464347)](fg:#1e222a)"
vicmd_symbol = "[[](bg:#1e222a fg:#464347)[](bg:#464347 fg:#1e222a)](bold bg:#6f6a70 fg:#1e222a)"
format = "$symbol"

[username]
style_user = "bold bg:purple fg:#1e222a"
style_root = "bold red"
show_always = true
format = "[](bg:purple fg:#464347)[ $user ]($style)[](bg:#464347 fg:purple)"

[directory]
style = "bold bg:blue fg:#1e222a"
read_only = " "
read_only_style = "bold bg:blue fg:#282c34"
truncation_length = 1
format = "[](bg:blue fg:#464347)[ $path ]($style)[$read_only]($read_only_style)[](bg:#464347 fg:blue)"

[git_status]
style = "bold bg:red fg:#1e222a"
stashed = " ${count}"
ahead = "ﲗ ${count}"
behind = "ﲔ ${count}"
diverged = "李 ${ahead_count} ${behind_count}"
conflicted = "${count}"
deleted = " ${count}"
renamed = "﫦${count}"
modified = " 凜${count}"
staged = "  ${count}"
untracked = "  ${count}"
disabled = true
format = "[](bg:red fg:#464347)[ $stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind ]($style)[](bg:#464347 fg:red)"

[git_branch]
style = "bold bg:green fg:#1e222a"
symbol = ""
format = "[](bg:green fg:#464347)[ $branch ]($style)[](bg:#464347 fg:green)"
