###  FORMAT  ###

format = '[](red)[](green)[](yellow) [ ](cyan)$git_branch$git_status $directory '

###  MISC  ###

add_newline = true

###  MODULES  ##

[time]
time_format = "%T"
format = "[ $time]($style)"
style = "cyan"
disabled = false

[directory]
style = "bold cyan"
truncation_length = 1
format = "[$path]($style)"

##  GIT  ##

[git_branch]
format = " [](yellow)[$symbol$branch]($style)"
symbol = ""
style = "bg:yellow fg:#1e222a"

[git_status]
diverged = " [李${ahead_count} ${behind_count}](bg:yellow fg:#1e222a)"
untracked = " [ ${count}](bg:yellow fg:#1e222a)"
staged = " [⏽${count}](bg:yellow fg:#1e222a)"
modified = " [凜${count}](bg:yellow fg:#1e222a)"
deleted = " [﫧${count}](bg:yellow fg:#1e222a)"
format = "[$modified$deleted$staged$untracked$diverged](bg:yellow fg:#1e222a)[](yellow)"
