# Inserts a blank line between shell prompts
add_newline = true

# Use custom format
format = """
[ ┌───────────────────>](bold green)
[ │ ](bold green)$directory$rust$package$git_branch$git_status
[ └─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
