format = '[[[](fg:blue)[](bg:blue fg:#282c34)[](bg:#282c34 fg:blue)](bg:blue) [$directory](bg:#282c34)[](fg:#282c34)](bg:#282c34) '
add_newline = true

[directory]
style = "bg:#282c34 fg:blue"
truncation_length = 1
format = "[$path]($style)"
