format = '[[[](fg:blue)[](bg:blue fg:#333333)[](bg:#333333 fg:blue)](bg:blue) [$directory](bg:#333333)[](fg:#333333)](bg:#333333) '
add_newline = true

[directory]
style = "bg:#333333 fg:blue"
truncation_length = 1
format = "[$path]($style)"
